[package]
name = "sociedade-walingardyana"
version = "0.1.0"
description = "Site da Sociedade Walingardyana"
license = "MIT"

[dependencies]

[[command]]
name = "web"
module = "public"
runner = "web"

[fs]
public = "."
